// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1MMr4lN3CDDZPW68NSndXJnYC1ZJsbCc',
    appId: '1:911429912004:web:225a78890a963850671091',
    messagingSenderId: '911429912004',
    projectId: 'absensi-sekolah-47534',
    authDomain: 'absensi-sekolah-47534.firebaseapp.com',
    storageBucket: 'absensi-sekolah-47534.firebasestorage.app',
    measurementId: 'G-634JE5F85Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW6llh4Lo-kp6LCai2PIH3dVlMAaGr0cA',
    appId: '1:911429912004:android:8daaf072cef1aade671091',
    messagingSenderId: '911429912004',
    projectId: 'absensi-sekolah-47534',
    storageBucket: 'absensi-sekolah-47534.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtgCmiKuHaIKpim38_Qxvsrpm5SMV6IYk',
    appId: '1:911429912004:ios:798abd52d01bc559671091',
    messagingSenderId: '911429912004',
    projectId: 'absensi-sekolah-47534',
    storageBucket: 'absensi-sekolah-47534.firebasestorage.app',
    iosBundleId: 'com.',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtgCmiKuHaIKpim38_Qxvsrpm5SMV6IYk',
    appId: '1:911429912004:ios:2277ef5763763280671091',
    messagingSenderId: '911429912004',
    projectId: 'absensi-sekolah-47534',
    storageBucket: 'absensi-sekolah-47534.firebasestorage.app',
    iosBundleId: 'com.example.absensiSiswa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1MMr4lN3CDDZPW68NSndXJnYC1ZJsbCc',
    appId: '1:911429912004:web:4c4fe3f4269e61cf671091',
    messagingSenderId: '911429912004',
    projectId: 'absensi-sekolah-47534',
    authDomain: 'absensi-sekolah-47534.firebaseapp.com',
    storageBucket: 'absensi-sekolah-47534.firebasestorage.app',
    measurementId: 'G-J8XX3C8WQQ',
  );
}
